sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

php:
  - '7.3'
install:
  - travis_retry composer install $COMPOSER_ARGS
  - travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS
  - composer show
  - cat phpunit.xml
script:
  - composer test-coverage
  - composer cs-check
  - composer license-check
  - composer phpstan
after_script:
  - vendor/bin/php-coveralls -v